# hardware.nix - Hardware-specific configuration generated by nixos-generate-config
{ self, inputs, ... }: 

{
  flake.nixosModules.pcHardware = { config, lib, pkgs, modulesPath, ... }:

  {
    imports =
      [ (modulesPath + "/installer/scan/not-detected.nix")
      ];

    boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ]; # AMD processor virtualization support
    boot.extraModulePackages = [ ];

    # File systems and partition UUIDs
    fileSystems."/" =
      { device = "/dev/disk/by-uuid/a61b9668-4ae4-49c4-972d-c7e8147cb3fa";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/D022-36C3";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices = [ ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}